SOURCES:=$(wildcard src/*.lua)
EXTENSIONS:=$(wildcard extensions/*.lua)
OUTPUT:=plug.lua

.PHONY: %.lua plug.lua src/00_header.lua src/99_footer.lua

$(SOURCES): %.lua
$(EXTENSIONS): %.lua

%.lua:
	@echo
	@cat $@

header:
	@echo '------------------------------------------'
	@echo '-- this file is automatically generated --'
	@echo '--        do not edit directly          --'
	@echo '------------------------------------------'
	@cat src/00_$@.lua

footer:
	@echo
	@cat src/99_$@.lua

preview: header $(SOURCES) $(EXTENSIONS) footer

compile:
	@$(MAKE) preview > $(OUTPUT)

testrun: compile
	@nvim -u tests/init.lua

testrun-auto:
	@nvim -u tests/auto.lua
