SOURCES:=$(sort $(wildcard src/*.lua))
BACKENDS:=$(sort $(wildcard backends/*.lua))
EXTENSIONS:=$(sort $(wildcard extensions/*.lua))
OUTPUT:=plug.lua

.PHONY: %.lua plug.lua src/00_header.lua src/99_footer.lua

$(SOURCES): %.lua
$(BACKENDS): %.lua
$(EXTENSIONS): %.lua

%.lua:
	@echo
	@cat $@

header:
	@echo '------------------------------------------'
	@echo '-- this file is automatically generated --'
	@echo '--        do not edit directly          --'
	@echo '------------------------------------------'
	@echo "local build_timestamp = \"$(shell date '+%d %b %Y %H:%M:%S')\""
	@cat src/00_$@.lua

footer:
	@echo
	@cat src/99_$@.lua

preview: header $(SOURCES) $(BACKENDS) $(EXTENSIONS) footer

compile:
	@$(MAKE) preview > $(OUTPUT)

testrun: compile
	@nvim -u tests/init.lua

testrun-auto:
	@nvim -u tests/auto.lua
