SOURCES:=$(sort $(wildcard src/*.lua))
BACKENDS:=$(sort $(wildcard backends/*.lua))
EXTENSIONS:=$(sort $(wildcard extensions/*.lua))
OUTPUTPATH:=
OUTPUT:=plug.lua
TEMPDIR:=$(shell mktemp -d)
PLACEHOLDER=to be calculated at compile time
CONFIGPATH=$$$$HOME/.config
DATAPATH=$$$$HOME/.local/share
TESTNAME=plug.nvim

.PHONY: %.lua plug.lua src/00_header.lua src/99_footer.lua test-auto-% test-%

$(SOURCES): %.lua
$(BACKENDS): %.lua
$(EXTENSIONS): %.lua

%.lua:
	@echo
	@cat $@

header:
	@echo '------------------------------------------'
	@echo '-- this file is automatically generated --'
	@echo '--        do not edit directly          --'
	@echo '------------------------------------------'
	@echo "local build_checksum = \"$(PLACEHOLDER)\""
	@cat src/00_$@.lua

footer:
	@echo
	@cat src/99_$@.lua

preview: header $(SOURCES) $(BACKENDS) $(EXTENSIONS) footer

compil%:
	@$(MAKE) preview > $(TEMPDIR)/$(OUTPUT)
	@CHECKSUM="$$(b2sum -l 256 $(TEMPDIR)/$(OUTPUT) | cut -d' ' -f1)" && \
	sed "s/\"$(PLACEHOLDER)\"/\"$$CHECKSUM\"/g" $(TEMPDIR)/$(OUTPUT) > $(OUTPUTPATH)$(OUTPUT)

backend.%:
	@sed 's/plug\.backend/plug.$@/g' $(TEMPDIR)/test.lua > $(TEMPDIR)/init.lua

init:
	$(eval TEMPDIR="$(CONFIGPATH)/$(TESTNAME)")
	@mkdir -p "$(TEMPDIR)"
	$(eval OUTPUTPATH="$(DATAPATH)/$(TESTNAME)/site/pack/plug/opt/plug.nvim/lua/")
	@mkdir -p "$(OUTPUTPATH)"

tests/%:
	@cat "$@.lua" > "$(TEMPDIR)/test.lua"

clean: init
	$(eval TEMPDIR="$(CONFIGPATH)/$(TESTNAME)")
	@rm -rf "$(TEMPDIR)"
	$(eval DATAPATH="$(DATAPATH)")
	@rm -rf "$(DATAPATH)/$(TESTNAME)"

drytest-auto-%: tests/auto backend.% compile
	@cat $(TEMPDIR)/init.lua

drytest-%: tests/init backend.% compile
	@cat $(TEMPDIR)/init.lua

run-%:
	@NVIM_APPNAME="$(TESTNAME)" nvim

test-auto-%: tests/auto backend.% compile init run-test;

test-%: init tests/init backend.% compile run-test;
