name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build plug.nvim
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate plug.lua
        run: |
          make --no-print-directory compile
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'plug.lua'
          default_author: github_actions
          message: 'ci: automatic code generation'
