name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Release plug.nvim
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate plug.lua
        run: |
          make --no-print-directory compile
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 22
          extra_plugins: |
            @semantic-release/release-notes-generator@12
            conventional-changelog-conventionalcommits@7
            @semantic-release/changelog@6
            @semantic-release/git@10
